### ISSUE TITLE
Enhanced Sync Page and Organization Management

### ISSUE THREAD

**Issue by hootanht** [cs-internship/cs-system#30]
The current Sync page design lacks optimal user experience, and there is a need for the introduction of Organization management features. This feature request aims to enhance the Sync page design and introduce functionalities for efficient Organization management.

 Proposed Changes:

1\. Sync Page Design:  
  - Revise the layout and visual elements of the Sync page for a more intuitive and aesthetically pleasing experience.  
  - Implement responsive design principles to ensure a seamless experience across various devices.  
  - Consider adding visual indicators for sync status and progress.

2\. Organization Management:  
  - Introduce a dedicated section for managing Organizations within the application.  
  - Allow users to create, edit, and delete Organizations as needed.  
  - Implement user roles and permissions for enhanced organizational control.

 Expected Impact:  
\- Improved User Experience: A redesigned Sync page will provide users with a more user-friendly and visually appealing interface.  
\- Efficient Organization Management: Users will be able to organize and manage their data more effectively through the addition of Organization management features.

 Additional Considerations:  
\- Accessibility: Ensure that the changes adhere to accessibility standards for users with diverse needs.  
\- User Guidance: Provide clear documentation and tooltips to guide users through the new Sync page and Organization management features.  
\- Testing: Conduct thorough testing to identify and address any potential usability issues.

 Use Case:  
Users often interact with the Sync page to manage data synchronization, and the introduction of Organization management will contribute to better organization and control over their data.

**Comment by Ali-Sdg90** [comment]
Hello, I have designed a layout for the select organization feature, and I would appreciate feedback on it before proceeding with its implementation in the project.

Figma design link: https://www.figma.com/file/mSm3H5uERXWhwZkzhwmek2/CS-SYSTEM---Select-Organization?type=design&node-id=0%3A1&mode=design&t=Xeyo2kfZlqvgJZjB-1

@mehrandvd @hootanht

**Comment by hootanht** [comment]
I believe renaming the header to 'Manage Organization' would provide clearer guidance for users compared to 'Select Your Organization'. Additionally, enhancing the user interface with edit and delete icons alongside each action button, such as the plus symbol, and incorporating color coding - green for addition, red for deletion, and yellow for editing - would significantly improve user interaction and streamline tasks within the component.

**Comment by Ali-Sdg90** [comment]
I've made some changes to the design. Please take a look at it, and if you have any additional feedback or notes, please share them. Thanks

https://www.figma.com/file/mSm3H5uERXWhwZkzhwmek2/CS-SYSTEM---Select-Organization?type=design&node-id=0%3A1&mode=design&t=M6cMNuYwydLkRKqr-1

@hootanht

**Comment by hootanht** [comment]
> I've made some changes to the design. Please take a look at it, and if you have any additional feedback or notes, please share them. Thanks
> 
> https://www.figma.com/file/mSm3H5uERXWhwZkzhwmek2/CS-SYSTEM---Select-Organization?type=design&node-id=0%3A1&mode=design&t=M6cMNuYwydLkRKqr-1
> 
> @hootanht 

How about making the button background change to the border color when users hover over them? Everything else seems fine! 👌

**Comment by Ali-Sdg90** [comment]
That's the plan 😉

**Comment by hootanht** [comment]
Ok, let's start implementation if you have any suggestions tell us @mehrandvd.

**Comment by mehrandvd** [comment]
@Ali-Sdg90  Wowww... It's a great job that you've brought figma into the game :)
Let's talk about it on a Teams call

**Comment by hootanht** [comment]
@Ali-Sdg90 Can you set this meeting for this sprint?
