### ISSUE TITLE
Create a GitHub repo as a test CS Org

### ISSUE THREAD

**Issue by hootanht** [cs-internship/cs-system#31]
As part of organizational improvements, there is a need to create a dedicated repository specifically for the CS Internship test project. This will help in better organization, version control, and collaboration on the test project.

 Proposed Implementation:

1\. Create Dedicated Repository:  
  - Establish a new GitHub repository with an appropriate name for the CS Internship test project.

2\. Repository Structure:  
  - Organize the repository with clear directory structures, considering different components or stages of the test project.  
  - Set up a README file providing essential information about the project, including setup instructions and guidelines for contributors.

3\. Access Permissions:  
  - Define and configure access permissions to ensure that only relevant team members have appropriate access to the repository.

 Expected Outcome:  
- A dedicated GitHub repository specifically for the CS Internship test project with a well-organized structure and proper documentation.

 Additional Considerations:  
- Collaboration Guidelines: Include guidelines on collaboration, branching strategies, and code review processes in the README file.  
- Issue Tracking: Utilize GitHub Issues to track tasks, enhancements, and bugs related to the test project.  
- Continuous Integration: Integrate with a CI/CD system if applicable to automate testing and deployment processes.

 Use Case:  
The dedicated repository will streamline collaboration among CS Internship team members, providing a centralized and organized space for managing the test project.

**Comment by hootanht** [comment]
Create the test repo under cs-internship.
After the base test repo was created, this folder which is used as a sample for tests should be moved to the newly created base test repo.
Replace new URLs in test methods.
![image](https://github.com/cs-internship/cs-system/assets/27281206/d3ad8cbb-b81d-4bc4-9892-5fef7c21a77b)
@BSeyfi

**Comment by mehrandvd** [comment]
I found the document a bit challenging to decipher, but if I’ve grasped it correctly, it seems this repository is intended to serve as an example for a _"CS Organization"_. It will include sample documents and badges. If my understanding aligns with the purpose, how about we consider the name `sample-org-contoso`? It has a nice ring to it! 😊
@hootanht @BSeyfi

**Comment by hootanht** [comment]
Agree with `sample-org-contoso`.
@mehrandvd

**Comment by mehrandvd** [comment]
It's now available at: https://github.com/cs-internship/sample-org-contoso
@BSeyfi

**Comment by hootanht** [comment]
Thanks a lot.
@mehrandvd
