### ISSUE TITLE
Enhance the Style of the Badge Explorer Page

### ISSUE THREAD

**Issue by Ali-Sdg90** [cs-internship/cs-system#50]
We aim to enhance the visual style of the "Badge Explorer" page for each organization. The "Badge Explorer" page displays a list of badges available for exploration within each organization. The desired layout includes a collapsible tree menu on the left for navigating categories and badges, and a section on the right for displaying badge details when a badge is clicked. The badge details will be populated with JSON data.

### Additional Notes

- No changes to the current functionality are required. 
- Ensure consistency with Bootstrap framework guidelines, as the project utilizes Bootstrap as its style framework.
- Ensure the style is responsive to adapt to various screen sizes.

### Steps to Participate

1. Comment on this issue with your estimated timeframe for completing the task.
2. The administrators will review your proposed timeline.
3. If approved, the issue will be assigned to you.
4. Upon successful completion within the agreed timeframe, you'll receive the issue reward.

### Contribution Guidelines:

Please refer to the [Contribution Guidelines](https://github.com/cs-internship/cs-system/blob/develop/docs/standards/contribution.md) for detailed instructions on contributing to the project.

### Badge JSON Data:

For detailed information on the structure of badge JSON data, refer to the [Badge Model Documentation](https://github.com/cs-internship/cs-system/blob/develop/docs/technical/models.md#badge). An example JSON badge is available [here](https://github.com/cs-internship/cs-system/blob/develop/src/CrystallineSociety/Shared/CrystallineSociety.Shared.Test/BadgeSystem/SampleBadgeDocs/github-sample-folder/documenation/doc-beginner-badge.json).

### Deliverables
 - The PR for the final "Badge Explorer" should be approved by @mehrandvd he will announce his approval on this issue.

### Reward
 - The reward will be **50$** which will be paid in $USDC

**Comment by mehrandvd** [comment]
@Ali-Sdg90 I don't understand which page or component does "Badge Page" refer to? A component that represents a single badge, or the component that represents a list of badges to explore.

**Comment by Ali-Sdg90** [comment]
@mehrandvd Thank you for your question. The "Badge Page" refers to the component that displays a list of badges to explore for each organization. I have updated the issue text to clarify this.

**Comment by mehrandvd** [comment]
In this case "Badge Page" wouldn't be a good name. "Badges Page", or even "Badge Explorer" would be the more proper names.

**Comment by Ali-Sdg90** [comment]
I will deliver this task in 14 days (by 2024-06-21).

@mehrandvd

**Comment by mehrandvd** [comment]
> I will deliver this task in 14 days (by 2024-06-21).
> 
> @mehrandvd 

Great, it's yours :)

**Comment by Ali-Sdg90** [comment]
After our meeting to review my pull request, I found out that I needed to complete additional parts of the task. Therefore, I will extend my deadline to 2024-07-05.

@mehrandvd

**Comment by mehrandvd** [comment]
> After our meeting to review my pull request, I found out that I needed to complete additional parts of the task. Therefore, I will extend my deadline to 2024-07-05.
> 
> @mehrandvd

Thank you for letting me know

**Comment by Ali-Sdg90** [comment]
Hi @mehrandvd,

The foundational style and functionality for the badge page have been implemented in this pull request. I believe this level of progress is sufficient for this issue. We will continue improving the page in future issues.

Link to the pull request: https://github.com/cs-internship/cs-system/pull/54

Screenshot of the current page:

![photo_2024-07-05_16-14-26](https://github.com/cs-internship/cs-system/assets/115698554/8d6cd19c-5d7e-4ba7-8e04-8ca08882f383)

**Comment by mehrandvd** [comment]
@Ali-Sdg90 Thank you Ali. The work is approved now.
Please send your USDC(ERC20) wallet address here so we can reward 50$ for your contribution :)

**Comment by Ali-Sdg90** [comment]
> @Ali-Sdg90 Thank you Ali. The work is approved now. Please send your USDC(ERC20) wallet address here so we can reward 50$ for your contribution :)

Thanks :)
My USDC receive address: 0x2649A458028460e42053f9D69EfFC7cE39c837d6

**Comment by mehrandvd** [comment]
@Ali-Sdg90 Your **50$** reward is paid :)
https://etherscan.io/tx/0x294f0797af278ba1d891fe87701de1162334fc5cb5f71d5634d927f9b0cf70b1

Congratulations, you have the first payment for the CS Internship!
https://github.com/cs-internship/cs-finance/blob/main/accounting/expenses.md

**Comment by arivale-exe** [comment]
I can complete the responsive Bootstrap Badge Explorer UI enhancement within 1–2 days after assignment. Before implementation, could you confirm the payout network and recipient process: is payment $50 USDC on Solana, and can it be sent to the contributor-provided Solana/KAST destination after @mehrandvd approves and announces the PR?

**Comment by mehrandvd** [comment]
@arivale-exe Thanks for your comment, but this task is completed and the payment has already been made, as you can see:

> [@Ali-Sdg90](https://github.com/Ali-Sdg90) Your **50$** reward is paid :) https://etherscan.io/tx/0x294f0797af278ba1d891fe87701de1162334fc5cb5f71d5634d927f9b0cf70b1
> 
> Congratulations, you have the first payment for the CS Internship! https://github.com/cs-internship/cs-finance/blob/main/accounting/expenses.md
