### ISSUE TITLE
Enhance Visual Style and Fix Bugs in "Badge Explorer" Page - Part 1

### ISSUE THREAD

**Issue by Ali-Sdg90** [cs-internship/cs-system#55]
We aim to enhance the visual style of the "Badge Explorer" page implemented in another issue (https://github.com/cs-internship/cs-system/issues/50). The desired layout includes a collapsible tree menu on the left for navigating categories and badges and a section on the right for displaying badge details when a badge is clicked. 

This issue focuses on improving visual details and ensuring the page is bug-free. 
The improvements are divided into two issues.

#### Left Section:
1. Update the left menu to look like [Collapsible Menu](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-digital-twins-builder) Preferably with smooth animation for opening and closing. It should be usable for nested folder scenarios
2. Add loading indicators when badges are not fetched.
3. Ensure the search bar has equal spacing on all sides in its section.
4. Reduce the font size and spacing of the menu and make it fit on the page.
5. Make the section height responsive to the user's display height.

#### Right Section:
6. Make the section height equal to the left menu.
7. Increase the badge icon's size next to the badge's title.
8. Change the title box background to transparent.
9. Make the section height responsive to the user's display height.
10. Use the "Bootstrap Tab" structure for tab buttons.
11. Make sure the UI is ok with multi-paragraph descriptions.

![CS-System - p12](https://github.com/cs-internship/cs-system/assets/115698554/e2183cac-988e-4cd7-b177-e097795788fc)

### Additional Notes
- Ensure consistency with Bootstrap framework guidelines, as the project utilizes Bootstrap as its style framework.
- Ensure the style is responsive to adapt to various screen sizes.

### Steps to Participate
1. Comment on this issue with your estimated timeframe for completing the task.
2. The administrators will review your proposed timeline.
3. If approved, the issue will be assigned to you.
4. Upon successful completion within the agreed timeframe, you'll receive the issue reward.

### Contribution Guidelines
Please refer to the [Contribution Guidelines](https://github.com/cs-internship/cs-system/blob/develop/docs/standards/contribution.md) for detailed instructions on contributing to the project.

### Deliverables
- The PR for this issue should be approved by @mehrandvd. He will announce his approval on this issue.

### Reward
- The reward will be **$30**, which will be paid in $USDC.

**Comment by ZahraaaRezaeiii** [comment]
Hello @mehrandvd,
I will deliver this task in 15 days (by 2024-07-26).

**Comment by mehrandvd** [comment]
> Hello @mehrandvd, I will deliver this task in 15 days (by 2024-07-26).

It's yours now :)

**Comment by ZahraaaRezaeiii** [comment]
Thanks a lot @mehrandvd

**Comment by ZahraaaRezaeiii** [comment]
Hi @mehrandvd 

Link to the pull request of this task: https://github.com/cs-internship/cs-system/pull/57

Screenshot of the current page:
![image](https://github.com/user-attachments/assets/3aacf026-14f7-4c5a-9afa-59a954ad5421)

**Comment by mehrandvd** [comment]
@ZahraaaRezaeiii It looks pretty!
What are those **Disabled** tabs?

**Comment by mehrandvd** [comment]
@ZahraaaRezaeiii Can you share an image of a badge, having some badge requirements and activity requirements and approval steps for it?

**Comment by ZahraaaRezaeiii** [comment]
Thank you @mehrandvd 
About your question, these are placeholders for other information we want to show the user about the site later.
Later, these parts will be able to display their tab name. 
To implement and display the final state of the page, I needed to place these tabs here as placeholders.

**Comment by ZahraaaRezaeiii** [comment]
@mehrandvd  Yes, sure

Screenshot of the current page after clicking on the doc-guru badge, which contains badge requirements, activity requirements, and approval steps information.
![image](https://github.com/user-attachments/assets/69db094b-d14f-4753-9b5c-a39f17600168)

**Comment by mehrandvd** [comment]
@ZahraaaRezaeiii Cool, for the badges please use the bootstrap's [badge component](https://getbootstrap.com/docs/4.0/components/badge/).

**Comment by Ali-Sdg90** [comment]
> @ZahraaaRezaeiii Cool, for the badges please use the bootstrap's [badge component](https://getbootstrap.com/docs/4.0/components/badge/).

Hi @mehrandvd,

In issue #56, item 6, I specified that "Bootstrap Badge" should be used for the badges. This will be updated in part two.

I have reviewed and confirmed that all points mentioned in this bug fix have been addressed in the pull request.

**Comment by ZahraaaRezaeiii** [comment]
@mehrandvd Thanks a lot
I have implemented all points mentioned in this bug fix, which have been addressed in the pull request.
As Ali said, this request is in item 6 of issue #56.  In this screenshot.
![image](https://github.com/user-attachments/assets/b9e201a8-8949-4700-bb9e-31aa5560c07f)

If you think it should be done in this issue, please tell me to do it.🙏

**Comment by mehrandvd** [comment]
@ZahraaaRezaeiii I see. Thank you for the good work.
This task is done now. Please send your USDC wallet address.

**Comment by ZahraaaRezaeiii** [comment]
> @ZahraaaRezaeiii I see. Thank you for the good work. This task is done now. Please send your USDC wallet address.

Thanks @mehrandvd 
My USDC receive address: 0xbf75d5fc95ac806ab2b4a0c8b31cd1b7a03b8625

**Comment by mehrandvd** [comment]
@ZahraaaRezaeiii Just to make sure, is it the ERC20?

**Comment by ZahraaaRezaeiii** [comment]
@mehrandvd I installed the Nobitex application and this is the page I took the address from.
![image](https://github.com/user-attachments/assets/80a463dc-7374-4fb1-ad3a-514a0f2a8e9f)
is it true?

**Comment by ZahraaaRezaeiii** [comment]
@mehrandvd  This is my new USDC receive address: 0xd616044e54e215a1AbFfb290082639BA986ea45f

**Comment by mehrandvd** [comment]
@ZahraaaRezaeiii Here's your 30$ reward in USDC:
https://etherscan.io/tx/0x68aca7341a1b035ad5ad4205a0c3cb2948551ec86d823bb6846d751e790ca1fa

Have fun :)
