### ISSUE TITLE
Fix Folder Opening Bug on "Badge Explorer" Page

### ISSUE THREAD

**Issue by Ali-Sdg90** [cs-internship/cs-system#58]
We aim to enhance the functionality of the "Badge Explorer" page, which was implemented in another issue (https://github.com/cs-internship/cs-system/issues/50). The desired layout includes a collapsible tree menu on the left for navigating categories and badges, and a section on the right for displaying badge details when a badge is clicked.

Currently, when a user clicks on a badge folder, all folders open. We want each folder to open and close independently, so that when a folder name is clicked, only that specific folder toggles open or closed.

![cs-6](https://github.com/user-attachments/assets/54a196d3-e734-421e-b3e6-a396f2634e7c)

### Additional Notes:
- Ensure consistency with Bootstrap framework guidelines, as the project utilizes Bootstrap as its style framework.
- Avoid adjusting default Bootstrap values as much as possible.
- Ensure the style is responsive and adapts to various screen sizes.

### Steps to Participate:
1. Comment on this issue with your estimated timeframe for completing the task.
2. The administrators will review your proposed timeline.
3. If approved, the issue will be assigned to you.
4. you'll receive the issue reward upon completing the agreed timeframe.

### Contribution Guidelines:
Please refer to the [Contribution Guidelines](https://github.com/cs-internship/cs-system/blob/develop/docs/standards/contribution.md) for detailed instructions on contributing to the project.

### Deliverables:
- The PR for this issue should be approved by @mehrandvd. He will announce his approval on this issue.

### Reward:
- The reward will be **$10**, which will be paid in $USDC (ERC20).

**Comment by hootanht** [comment]
I will work on this issue and finish that on 2024/08/20  
@mehrandvd

**Comment by mehrandvd** [comment]
Great, it's yours now :)

**Comment by Ali-Sdg90** [comment]
Pull Request provided by @hootanht for this issue: #60

**Comment by mehrandvd** [comment]
I guess this is done now, congratulations @hootanht. Please send your wallet for the reward :)

**Comment by hootanht** [comment]
> I guess this is done now, congratulations @hootanht. Please send your wallet for the reward :)

Thank you so much, @mehrandvd! A special thanks for creating this opportunity for developers to grow and thrive.

This is my USDC (ERC20) wallet address : `0xc47bc9980b8d728be392796f7e312961af4cff21`

**Comment by mehrandvd** [comment]
@hootanht Congratulations on your first paid task on the CS System.
Here's your 10$ reward for accomplishing this task: https://etherscan.io/tx/0x748f6c1f7710b96f715cc42bf03f25a1205c5e59af9167aefc8d7e07fea2ab24
