### ISSUE TITLE
Enhance the Visual Style of the "Organization Setting" Page

### ISSUE THREAD

**Issue by Ali-Sdg90** [cs-internship/cs-system#61]
We aim to refine the visual style of the "Organization Setting Page," which will act as a central hub for managing organizations within the CS System. This page will feature a primary table that displays the organizations connected to the CS System, with options to sync data, edit information, delete organizations, and add new organizations.

This task focuses solely on enhancing the page's visual design. While some button functionalities are not yet implemented, we need the buttons placed; future issues will address adding functionality.

You can access this page by clicking the "Organization" button located in the top-left corner of the main navigation bar, then selecting "Organization Setting" from the dropdown menu.

![CS-System - Org5](https://github.com/user-attachments/assets/3997641d-089d-4914-8b21-1b483ff3b573)

The "Sync" and "Delete" buttons must include a loading state when clicked, indicating that an asynchronous operation is in progress. Use the "Bootstrap Spinner" component as the loading indicator.

![ScreenRecording2024-08-12163233-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/2ee31baf-ea6c-4a79-979c-a593986f234d)

### Additional Notes
- Ensure consistency with Bootstrap framework guidelines, as the project utilizes Bootstrap as its style framework.
- Avoid adjusting default Bootstrap values as much as possible.
- Ensure the style is responsive to adapt to various screen sizes.

### Steps to Participate
1. Comment on this issue with your estimated timeframe for completing the task.
2. The administrators will review your proposed timeline.
3. If approved, the issue will be assigned to you.
4. you'll receive the issue reward upon completing the agreed timeframe.

### Contribution Guidelines
- Please refer to the [Contribution Guidelines](https://github.com/cs-internship/cs-system/blob/develop/docs/standards/contribution.md) for detailed instructions on contributing to the project.

### Deliverables
- The PR for this issue should be approved by @mehrandvd. He will announce his approval on this issue.

### Reward
- The reward will be **$5**, which will be paid in **$USDC (ERC20)**.

**Comment by hootanht** [comment]
0$?
@Ali-Sdg90

**Comment by mehrandvd** [comment]
@Ali-Sdg90  The "Add new organization" should align right, and the text should be like this: "**Add new organization**" (Not upper-first for all the words).
The title "Manage Organization" should align left with this text: "**Manage organizations**"

**Comment by Ali-Sdg90** [comment]
> 0$? @Ali-Sdg90

When the issue's content is finalized, the reward will be added.

**Comment by Ali-Sdg90** [comment]
Thanks, @mehrandvd, for your feedback! I've updated the issue image design. Please check it out.

I think aligning the title of the page to the left might be better. What do you think?

| Previous image | New image |
| --- | --- |
| ![CS-sync2](https://github.com/user-attachments/assets/9a207c0b-aa0f-4989-83e5-a175b64521b1) | ![Screenshot 2024-08-12 161524-Recovered3](https://github.com/user-attachments/assets/1f94e724-d9b2-4feb-a4d2-b690c573d704) |

| Align left  | Align right |
| --- | --- |
| | |
![Screenshot 2024-08-12 161524-Recovered4](https://github.com/user-attachments/assets/0a469c38-8227-4948-bdd5-636e69bf6f5a) | ![Screenshot 2024-08-12 161524-Recovered3](https://github.com/user-attachments/assets/10435705-4f2b-4dd5-abe3-0fc031489ddc) |

**Comment by mehrandvd** [comment]
> @Ali-Sdg90 The "Add new organization" should align right, and the text should be like this: "**Add new organization**" (Not upper-first for all the words).

@Ali-Sdg90 You've done it in reverse! The 'title' should go left, and the 'add button' goes right. I think that's the reason you have started suggesting the other different options.

**Comment by Ali-Sdg90** [comment]
> > @Ali-Sdg90 The "Add new organization" should align right, and the text should be like this: "**Add new organization**" (Not upper-first for all the words).
> 
> @Ali-Sdg90 You've done it in reverse! The 'title' should go left, and the 'add button' goes right. I think that's the reason you have started suggesting the other different options.

Oh... yes XD
I've updated the issue image. Is it okay now? :D

**Comment by mehrandvd** [comment]
@mehrandvd  Yes, it's ok now.
Another point to mention, for each action (add, edit, delete, sync), there should be a toast after the operation is completed, whether it is done successfully or failed for a reason.

**Comment by Ali-Sdg90** [comment]
@mehrandvd  Yes, I agree that we need to implement toast notifications for this page’s actions. However, I recommend addressing this in a separate issue since toast notifications should be managed globally across the project. Implementing toasts will require functionality, whereas this issue is primarily focused on styling. Additionally, another issue will be needed to cover full functionality, such as the edit, delete, and add buttons. In that issue, we can specify that toast notifications should be displayed after each action, indicating whether it was successful or not, along with relevant details.

**Comment by Ali-Sdg90** [comment]
> @mehrandvd Yes, I agree that we need to implement toast notifications for this page’s actions. However, I recommend addressing this in a separate issue since toast notifications should be managed globally across the project. Implementing toasts will require functionality, whereas this issue is primarily focused on styling. Additionally, another issue will be needed to cover full functionality, such as the edit, delete, and add buttons. In that issue, we can specify that toast notifications should be displayed after each action, indicating whether it was successful or not, along with relevant details.

If you agree with me, I will go ahead and create an issue for the global toast notification.

**Comment by mehrandvd** [comment]
@Ali-Sdg90  If the task is only about styling, it is OK, but it will be a tiny task.

**Comment by Ali-Sdg90** [comment]
@mehrandvd Yes, it's not a big task. Please specify the reward for completing the issue so that work can begin.
I'll create another issue for the global notification tomorrow.

**Comment by mehrandvd** [comment]
@Ali-Sdg90 I think 5$ would be OK for it.

**Comment by ZahraaaRezaeiii** [comment]
Hello @mehrandvd
I will deliver this task in 2 days (by 2024 - 8 - 22).

**Comment by mehrandvd** [comment]
@ZahraaaRezaeiii Great, it's your now :)

**Comment by ZahraaaRezaeiii** [comment]
https://github.com/user-attachments/assets/787d612b-d1be-4fd7-a1da-aca62dd8a6bf

**Comment by Ali-Sdg90** [comment]
Looks good to me. I reviewed the pull request, and it's fine. Good job, @ZahraaaRezaeiii👌

cc: @mehrandvd

**Comment by mehrandvd** [comment]
Thank you @ZahraaaRezaeiii, please send me your wallet to proceed with your reward payment.

**Comment by ZahraaaRezaeiii** [comment]
Thank you @mehrandvd 
This is my USDC receive address: 0xd616044e54e215a1AbFfb290082639BA986ea45f

**Comment by mehrandvd** [comment]
@ZahraaaRezaeiii just want to mention that I'm not forgetting to make this payment, but as it's very small, I'm waiting to aggregate it with your next reward, is it OK?

**Comment by ZahraaaRezaeiii** [comment]
@mehrandvd 
Yes, it's ok. Thanks

**Comment by mehrandvd** [comment]
> Thanks @mehrandvd If this amount has an additional transfer fee for you and is not cost-effective, it is okay.

@ZahraaaRezaeiii Since there were no other commits to aggregate this payment with for a while, I've completed this payment with the current transaction, and this issue is now resolved. Thanks for your great job :)
https://etherscan.io/tx/0xc985ad88357ab7d47c953b4a0f2cc436faa71f518dead78e51de6d9afd850528
